package Chp8;
class Employee{
    String name;
    int id;

    // This is No args ( user defined ) constructor where
    // we defined it without any args and by ourselves

//    Employee() {
//
//    }

    // This is default no argument constructor which is generated by compiler
    // when we have no other constructors

//    Employee() {
//        super;
//    }

    // This is parameterized constructor
    Employee (String n , int a) {
        this.name = n;
        this.id = a;
    }
}
public class Constructor {
    public static void main(String[] args) {
        // Constructor is a block which is similar to method having same name as of class name
        // It does not have any return type and not even void
        // The only modifier applicable for constructor are public , protected , default and private
        // When we create an object it executes automatically
        // It is mainly used to initialize object not create an object

        // Ways to call constructor :
        // 1. Test a = new Test();
        // 2. new Test(); no need of ref var here to call constructor
        Employee e1 = new Employee("Rohit",25);
        System.out.println(e1.id +" : "+ e1.name);

        // Types of constructors are :
        // 1. Default constructors ( no arg constructor )
        // 2. No argument constructors ( user defined )
        // 3. Parameterized constructors

        // 1. Default constructor : It is created by compiler not JVM

    }
}
